/* 07-screens 의 두 그림을 코드 안에 넣은 판을 만든다.
   npm run metri:screens

   아임웹은 올린 그림의 주소를 알려주는 화면이 따로 없다. 실제로 겪은 것은
   이렇다: 화면에 올려 게시한 뒤 우클릭해 주소를 복사하려 했더니 이미지
   메뉴가 아니라 페이지 메뉴가 떴다. 배경 이미지로 깔면 우클릭에 이미지
   항목이 아예 없고, 남은 길은 소스 보기나 검사 도구뿐이다. 코드 한 블록을
   붙이려고 개발자 도구를 여는 것은 주객이 전도된 일이다.

   그래서 주소를 안 쓴다. 그림을 코드에 실어 보내면 업로드도 주소도 필요
   없고, 나중에 파일을 옮기거나 지워도 그림이 사라지지 않는다.

   무손실 WebP 를 원본 크기 그대로 쓴다. 줄이면 오히려 커진다 — 리샘플링이
   없던 색을 수천 개 만들어내서 무손실 압축이 잡을 것을 잃는다. 실제로
   1120px 무손실이 21.8KB 인데 980px 로 줄이면 121KB 가 된다. */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import sharp from "sharp";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");
const IMG = join(root, "sites", "careermetri", "img-en");
const EN = join(root, "sites", "careermetri", "imweb-en");

const uri = async (name) => {
  const buf = await sharp(join(IMG, name))
    .webp({ lossless: true, effort: 6 })
    .toBuffer();
  return { uri: `data:image/webp;base64,${buf.toString("base64")}`, bytes: buf.length };
};

const test = await uri("test.png");
const report = await uri("report.png");

const src = readFileSync(join(EN, "07-screens.html"), "utf8");
const head = `<!-- GENERATED by npm run metri:screens. Do not edit by hand.

     07-screens with both screenshots carried inside the file, so there is
     nothing to upload and no address to find. Paste it and the pictures are
     there. Use this one when the host gives you no way to read back the
     address of an upload; use 07-screens.html when you have the addresses.

     Lossless WebP at the capture's own size. Both files together are about
     ${Math.round((test.bytes + report.bytes) / 1024)} KB, which is
     ${Math.round(((test.bytes + report.bytes) * 4) / 3 / 1000)} thousand
     characters once encoded, so the code widget is large. That is the price
     of not depending on a file that someone can move or delete later. -->\n`;

const out = head + src
  .replace(/^<!--[\s\S]*?-->\n/, "")
  .replace('src="IMG_TEST"', `src="${test.uri}"`)
  .replace('src="IMG_REPORT"', `src="${report.uri}"`);

writeFileSync(join(EN, "07-screens-embedded.html"), out);
console.log(
  `test ${(test.bytes / 1024).toFixed(1)}KB · report ${(report.bytes / 1024).toFixed(1)}KB` +
  ` → 07-screens-embedded.html ${(out.length / 1024).toFixed(1)}KB (${out.length.toLocaleString("ko-KR")}자)`
);
