/* 07-screens 의 그림을 코드 안에 넣은 판을 만든다.
   npm run metri:screens

   아임웹은 올린 그림의 주소를 알려주는 화면이 따로 없다. 실제로 겪은 것은
   이렇다: 화면에 올려 게시한 뒤 우클릭해 주소를 복사하려 했더니 이미지
   메뉴가 아니라 페이지 메뉴가 떴다. 배경 이미지로 깔면 우클릭에 이미지
   항목이 아예 없고, 남은 길은 소스 보기나 검사 도구뿐이다. 코드 한 블록을
   붙이려고 개발자 도구를 여는 것은 주객이 전도된 일이다.

   그래서 주소를 안 쓴다. 그림을 코드에 실어 보내면 업로드도 주소도 필요
   없고, 나중에 파일을 옮기거나 지워도 그림이 사라지지 않는다.

   무손실 WebP 를 쓴다. 두 번 재 보고 정한 것이다.

   하나, 줄이면 오히려 커진다 — 리샘플링이 없던 색을 수천 개 만들어내서
   무손실 압축이 잡을 것을 잃는다. 1120px 무손실 21.8KB 가 980px 에서는
   121KB 가 됐다. 그래서 찍은 크기 그대로 둔다.

   둘, 손실 압축이 더 크다. 화면 사진은 단색 면과 또렷한 글자로 되어 있어
   무손실이 잘 듣는다. 여섯 장 합계가 무손실 165KB 인데 품질 95 로 주면
   381KB 다. 흐려지는 값을 치르고 두 배를 받는 셈이라 쓸 이유가 없다.

   가벼운 판을 같이 낸다. 여섯 장이면 22만 자라 코드 위젯이 꽤 커지는데,
   그 host 가 어디서 손을 드는지는 붙여 봐야 안다. 세 장짜리를 같이 내
   두면 거기서 막혔을 때 되돌아올 자리가 있다. */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import sharp from "sharp";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..", "..");
const IMG = join(root, "sites", "careermetri", "img-en");
const EN = join(root, "sites", "careermetri", "imweb-en");

/* 자리 표시자와 파일의 짝. 가벼운 판에 남길 셋은 keep 이다 —
   응시 화면, 요약, 직무 열 개. 무엇이 어떻게 생겼는지, 무엇이 나오는지,
   무엇을 재는지 세 가지에 답한다. */
const SHOTS = [
  { slot: "IMG_SITTING",        file: "test.png",     keep: true },
  { slot: "IMG_REPORT_SUMMARY", file: "summary.png",  keep: true },
  { slot: "IMG_REPORT_AREAS",   file: "jobareas.png", keep: true },
  { slot: "IMG_REPORT_AXES",    file: "prefs.png",    keep: false },
  { slot: "IMG_REPORT_ROLES",   file: "rolefit.png",  keep: false },
  { slot: "IMG_REPORT_NEXT",    file: "next.png",     keep: false },
];

for (const s of SHOTS) {
  const buf = await sharp(join(IMG, s.file)).webp({ lossless: true, effort: 6 }).toBuffer();
  s.uri = `data:image/webp;base64,${buf.toString("base64")}`;
  s.bytes = buf.length;
}

const src = readFileSync(join(EN, "07-screens.html"), "utf8").replace(/^<!--[\s\S]*?-->\n/, "");
const kb = (list) => Math.round(list.reduce((n, s) => n + s.bytes, 0) / 1024);

/* 슬라이드 하나를 통째로 걷어낸다. src 만 지우면 자리 표시자를 주소로 삼아
   서버로 요청이 나가고, 깨진 그림 자리와 설명글만 남는다. */
const dropSlide = (html, slot) =>
  html.replace(new RegExp(`\\s*<div class="cm-slide"><figure>\\s*<img src="${slot}"[\\s\\S]*?</figure></div>`), "");

function build(list, name, note) {
  let html = src;
  for (const s of SHOTS) {
    html = list.includes(s)
      ? html.replace(`src="${s.slot}"`, `src="${s.uri}"`)
      : dropSlide(html, s.slot);
  }
  html = html.replace(/aria-label="Six screens"/, `aria-label="${list.length} screens"`);
  const head =
    `<!-- GENERATED by npm run metri:screens. Do not edit by hand.\n\n` +
    `     ${note}\n\n` +
    `     Lossless WebP at the size each screen was captured. The pictures\n` +
    `     together are about ${kb(list)} KB, which is ${Math.round(kb(list) * 1024 * 4 / 3 / 1000)}\n` +
    `     thousand characters once encoded, so the code widget is large. That\n` +
    `     is the price of not depending on a file someone can move or delete. -->\n`;
  const out = head + html;
  writeFileSync(join(EN, name), out);
  console.log(`${name.padEnd(30)} 슬라이드 ${list.length} · 그림 ${kb(list)}KB · ${out.length.toLocaleString("ko-KR")}자`);
}

build(SHOTS, "07-screens-embedded.html",
  "Every screen carried inside the file, so there is nothing to upload and no address to find.");
build(SHOTS.filter((s) => s.keep), "07-screens-embedded-light.html",
  "The same block with three screens instead of six, for a host that refuses the larger one.");
